name: 'Innovation Page Settings'
type: module
description: 'Provide more options to page settings'
package: Innovation
#core: '8.x'
core_version_requirement: ^8 || ^9
version: 9.x-1.0
dependencies:
  - inv_image_browser