name: Quick Settings
type: module
description: ' This module is used for showing features of the theme quickly'
package: Innovation
core_version_requirement: ^8 || ^9
version: '9.x-1.0'
#core: '8.x'

